---
engines:
  duplication:
    config:
      languages:
        - ruby
    enabled: true
  rubocop:
    checks:
      Rubocop/Metrics/ParameterLists:
        enabled: true
    enabled: true
exclude_paths:
  - rbunits/*
  - ressources/**
ratings:
  paths:
    - class/**
    - "**.rb"
