---
engines:
  duplication:
    config:
      languages:
        - ruby
    enabled: true
  rubocop:
    checks:
      Rubocop/Metrics/ParameterLists:
        enabled: false
    enabled: true
exclude_paths: 
  - rbunits/*
  - ressources/**
ratings:
  paths:
    - src/**
    - "**.rb"
